Single-quote output:dir controller-gen option.
The first argument of the shell invocation `controller-gen
output:dir="foo"` reaches controller-gen as output:dir=foo. Without
the quotes, certain values for output:dir confuse controller-gen's
option parsing as it attempts to guess the value's type. For example:

$ controller-gen output:dir="/tmp/tmp.1Pbg8eLCZK" # interpreted as an
invalid floating-point number
Error: unable to parse option "output:dir=/tmp/tmp.1Pbg8eLCZK": ['P'
exponent requires hexadecimal mantissa (at <input>:1:9) exponent has
no digits (at <input>:1:9)]